FROM postgres:17

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    postgresql-server-dev-17 \
    && rm -rf /var/lib/apt/lists/*

RUN cd /tmp \
    && git clone https://github.com/timescale/pg_textsearch.git \
    && cd pg_textsearch \
    && make \
    && make install \
    && rm -rf /tmp/pg_textsearch

# Enable shared preload
RUN echo "shared_preload_libraries = 'pg_textsearch'" >> /usr/share/postgresql/postgresql.conf.sample
