#pragma once

#include <stdbool.h>
#include <stdint.h>

typedef enum IcelandicPos {
  POS_NO = 0,
  POS_SO = 1,
  POS_LO = 2,
  POS_AO = 3,
  POS_FS = 4,
  POS_FN = 5,
  POS_ST = 6,
  POS_TO = 7,
  POS_GR = 8,
  POS_UH = 9
} IcelandicPos;

typedef enum IcelandicContext {
  CTX_ANY = 0,
  CTX_BEFORE_NOUN = 1,
  CTX_BEFORE_VERB = 2,
  CTX_AFTER_PRONOUN = 3,
  CTX_SENTENCE_START = 4
} IcelandicContext;

typedef struct StopwordEntry {
  const char *word;
} StopwordEntry;

typedef struct ContextualStopwordEntry {
  const char *word;
  uint16_t pos_mask;
} ContextualStopwordEntry;

typedef struct DisambiguationRuleEntry {
  const char *word;
  IcelandicPos prefer;
  IcelandicPos over;
  IcelandicContext context;
} DisambiguationRuleEntry;

typedef struct PhraseEntry {
  const char *phrase;
  const char *lemma;
  bool is_stopword;
  IcelandicPos pos;
} PhraseEntry;

typedef struct PrepositionCaseEntry {
  const char *prep;
  uint8_t case_mask;
} PrepositionCaseEntry;

static const StopwordEntry ICELANDIC_STOPWORDS[] = {
  {"af"},
  {"alla"},
  {"allan"},
  {"allar"},
  {"allir"},
  {"allnokkra"},
  {"allnokkrar"},
  {"allnokkrir"},
  {"allnokkru"},
  {"allnokkrum"},
  {"allnokkur"},
  {"allnokkurn"},
  {"allnokkurra"},
  {"allnokkurrar"},
  {"allnokkurri"},
  {"allnokkurs"},
  {"allnokkurt"},
  {"allnokkuð"},
  {"allra"},
  {"allrar"},
  {"allri"},
  {"alls"},
  {"allt"},
  {"alltað"},
  {"allur"},
  {"andspænis"},
  {"annan"},
  {"annar"},
  {"annarra"},
  {"annarrar"},
  {"annarri"},
  {"annars"},
  {"annað"},
  {"annaðhvort"},
  {"auk"},
  {"austan"},
  {"austanundir"},
  {"austur"},
  {"að"},
  {"aðra"},
  {"aðrar"},
  {"aðrir"},
  {"bak"},
  {"beggja"},
  {"báða"},
  {"báðar"},
  {"báðir"},
  {"báðum"},
  {"bæði"},
  {"ef"},
  {"eftir"},
  {"ein"},
  {"eina"},
  {"einar"},
  {"einhver"},
  {"einhverja"},
  {"einhverjar"},
  {"einhverjir"},
  {"einhverju"},
  {"einhverjum"},
  {"einhvern"},
  {"einhverra"},
  {"einhverrar"},
  {"einhverri"},
  {"einhvers"},
  {"einir"},
  {"einn"},
  {"einna"},
  {"einnar"},
  {"einni"},
  {"eins"},
  {"einskis"},
  {"einu"},
  {"einum"},
  {"eitt"},
  {"eitthvað"},
  {"eitthvert"},
  {"ekkert"},
  {"ella"},
  {"ellegar"},
  {"en"},
  {"enda"},
  {"enga"},
  {"engan"},
  {"engar"},
  {"engin"},
  {"enginn"},
  {"engir"},
  {"engra"},
  {"engrar"},
  {"engri"},
  {"engu"},
  {"engum"},
  {"er"},
  {"eða"},
  {"eður"},
  {"fjarri"},
  {"fjær"},
  {"flestalla"},
  {"flestallan"},
  {"flestallar"},
  {"flestallir"},
  {"flestallra"},
  {"flestallrar"},
  {"flestallri"},
  {"flestalls"},
  {"flestallt"},
  {"flestallur"},
  {"flestöll"},
  {"flestöllu"},
  {"flestöllum"},
  {"fram"},
  {"frá"},
  {"fyrir"},
  {"fyrst"},
  {"fáein"},
  {"fáeina"},
  {"fáeinar"},
  {"fáeinir"},
  {"fáeinna"},
  {"fáeinum"},
  {"gagnstætt"},
  {"gagnvart"},
  {"gegn"},
  {"gegnt"},
  {"gegnum"},
  {"hana"},
  {"handa"},
  {"handan"},
  {"hann"},
  {"hans"},
  {"heldur"},
  {"hennar"},
  {"henni"},
  {"hin"},
  {"hina"},
  {"hinar"},
  {"hinir"},
  {"hinn"},
  {"hinna"},
  {"hinnar"},
  {"hinni"},
  {"hins"},
  {"hinu"},
  {"hinum"},
  {"hitt"},
  {"hið"},
  {"hjá"},
  {"honum"},
  {"hvað"},
  {"hvaða"},
  {"hvenær"},
  {"hver"},
  {"hverja"},
  {"hverjar"},
  {"hverjir"},
  {"hverju"},
  {"hverjum"},
  {"hvern"},
  {"hverra"},
  {"hverrar"},
  {"hverri"},
  {"hvers"},
  {"hvert"},
  {"hvor"},
  {"hvora"},
  {"hvorar"},
  {"hvorir"},
  {"hvorki"},
  {"hvorn"},
  {"hvorra"},
  {"hvorrar"},
  {"hvorri"},
  {"hvors"},
  {"hvort"},
  {"hvoru"},
  {"hvorug"},
  {"hvoruga"},
  {"hvorugan"},
  {"hvorugar"},
  {"hvorugir"},
  {"hvorugra"},
  {"hvorugrar"},
  {"hvorugri"},
  {"hvorugs"},
  {"hvorugt"},
  {"hvorugu"},
  {"hvorugum"},
  {"hvorugur"},
  {"hvorum"},
  {"hvílík"},
  {"hvílíka"},
  {"hvílíkan"},
  {"hvílíkar"},
  {"hvílíkir"},
  {"hvílíkra"},
  {"hvílíkrar"},
  {"hvílíkri"},
  {"hvílíks"},
  {"hvílíkt"},
  {"hvílíku"},
  {"hvílíkum"},
  {"hvílíkur"},
  {"hún"},
  {"inn"},
  {"innan"},
  {"innanundir"},
  {"jafnframt"},
  {"jafnhliða"},
  {"kring"},
  {"kringum"},
  {"mestalla"},
  {"mestallan"},
  {"mestallar"},
  {"mestallir"},
  {"mestallra"},
  {"mestallrar"},
  {"mestallri"},
  {"mestalls"},
  {"mestallt"},
  {"mestallur"},
  {"mestöll"},
  {"mestöllu"},
  {"mestöllum"},
  {"með"},
  {"meðal"},
  {"meðan"},
  {"meður"},
  {"mig"},
  {"milli"},
  {"millum"},
  {"minn"},
  {"minna"},
  {"minnar"},
  {"minni"},
  {"mitt"},
  {"miðli"},
  {"mér"},
  {"mín"},
  {"mína"},
  {"mínar"},
  {"mínir"},
  {"míns"},
  {"mínu"},
  {"mínum"},
  {"mót"},
  {"móti"},
  {"nein"},
  {"neina"},
  {"neinar"},
  {"neinir"},
  {"neinn"},
  {"neinna"},
  {"neinnar"},
  {"neinni"},
  {"neins"},
  {"neinu"},
  {"neinum"},
  {"neitt"},
  {"nema"},
  {"neðan"},
  {"niður"},
  {"nokkra"},
  {"nokkrar"},
  {"nokkrir"},
  {"nokkru"},
  {"nokkrum"},
  {"nokkur"},
  {"nokkurn"},
  {"nokkurra"},
  {"nokkurrar"},
  {"nokkurri"},
  {"nokkurs"},
  {"nokkurt"},
  {"nokkuð"},
  {"norðan"},
  {"nálægt"},
  {"nær"},
  {"nærri"},
  {"næst"},
  {"næstum"},
  {"né"},
  {"nú"},
  {"of"},
  {"ofan"},
  {"ofar"},
  {"og"},
  {"okkar"},
  {"okkur"},
  {"oss"},
  {"sakir"},
  {"sama"},
  {"saman"},
  {"samar"},
  {"samfara"},
  {"samhliða"},
  {"sami"},
  {"samir"},
  {"samkvæmt"},
  {"samra"},
  {"samrar"},
  {"samri"},
  {"sams"},
  {"samskipa"},
  {"samt"},
  {"samtímis"},
  {"samur"},
  {"sem"},
  {"sig"},
  {"sinn"},
  {"sinna"},
  {"sinnar"},
  {"sinnhver"},
  {"sinnhverja"},
  {"sinnhverjar"},
  {"sinnhverjir"},
  {"sinnhverju"},
  {"sinnhverjum"},
  {"sinnhvern"},
  {"sinnhverra"},
  {"sinnhverrar"},
  {"sinnhverri"},
  {"sinnhvers"},
  {"sinnhvert"},
  {"sinnhvor"},
  {"sinnhvora"},
  {"sinnhvorar"},
  {"sinnhvorir"},
  {"sinnhvorn"},
  {"sinnhvorra"},
  {"sinnhvorrar"},
  {"sinnhvorri"},
  {"sinnhvors"},
  {"sinnhvort"},
  {"sinnhvoru"},
  {"sinnhvorum"},
  {"sinni"},
  {"sitt"},
  {"sitthvað"},
  {"sitthver"},
  {"sitthverja"},
  {"sitthverjar"},
  {"sitthverjir"},
  {"sitthverju"},
  {"sitthverjum"},
  {"sitthvern"},
  {"sitthverra"},
  {"sitthverrar"},
  {"sitthverri"},
  {"sitthvers"},
  {"sitthvert"},
  {"sitthvor"},
  {"sitthvora"},
  {"sitthvorar"},
  {"sitthvorir"},
  {"sitthvorn"},
  {"sitthvorra"},
  {"sitthvorrar"},
  {"sitthvorri"},
  {"sitthvors"},
  {"sitthvort"},
  {"sitthvoru"},
  {"sitthvorum"},
  {"sjálf"},
  {"sjálfa"},
  {"sjálfan"},
  {"sjálfar"},
  {"sjálfir"},
  {"sjálfra"},
  {"sjálfrar"},
  {"sjálfri"},
  {"sjálfs"},
  {"sjálft"},
  {"sjálfu"},
  {"sjálfum"},
  {"sjálfur"},
  {"slík"},
  {"slíka"},
  {"slíkan"},
  {"slíkar"},
  {"slíkir"},
  {"slíkra"},
  {"slíkrar"},
  {"slíkri"},
  {"slíks"},
  {"slíkt"},
  {"slíku"},
  {"slíkum"},
  {"slíkur"},
  {"snemma"},
  {"sum"},
  {"suma"},
  {"suman"},
  {"sumar"},
  {"sumir"},
  {"sumra"},
  {"sumrar"},
  {"sumri"},
  {"sums"},
  {"sumt"},
  {"sumu"},
  {"sumum"},
  {"sumur"},
  {"sunnan"},
  {"svo"},
  {"sá"},
  {"sér"},
  {"sérhvað"},
  {"sérhver"},
  {"sérhverja"},
  {"sérhverjar"},
  {"sérhverjir"},
  {"sérhverju"},
  {"sérhverjum"},
  {"sérhvern"},
  {"sérhverra"},
  {"sérhverrar"},
  {"sérhverri"},
  {"sérhvers"},
  {"sérhvert"},
  {"sín"},
  {"sína"},
  {"sínar"},
  {"sínhver"},
  {"sínhverja"},
  {"sínhverjar"},
  {"sínhverjir"},
  {"sínhverju"},
  {"sínhverjum"},
  {"sínhvern"},
  {"sínhverra"},
  {"sínhverrar"},
  {"sínhverri"},
  {"sínhvers"},
  {"sínhvert"},
  {"sínhvor"},
  {"sínhvora"},
  {"sínhvorar"},
  {"sínhvorir"},
  {"sínhvorn"},
  {"sínhvorra"},
  {"sínhvorrar"},
  {"sínhvorri"},
  {"sínhvors"},
  {"sínhvort"},
  {"sínhvoru"},
  {"sínhvorum"},
  {"sínir"},
  {"síns"},
  {"sínu"},
  {"sínum"},
  {"síðan"},
  {"síðla"},
  {"sökum"},
  {"söm"},
  {"sömu"},
  {"sömum"},
  {"sú"},
  {"til"},
  {"tráss"},
  {"um"},
  {"umfram"},
  {"umhverfis"},
  {"undan"},
  {"undir"},
  {"uns"},
  {"upp"},
  {"utan"},
  {"vegna"},
  {"vestan"},
  {"vestur"},
  {"vettugi"},
  {"við"},
  {"viður"},
  {"vor"},
  {"vora"},
  {"vorar"},
  {"vorir"},
  {"vorn"},
  {"vorra"},
  {"vorrar"},
  {"vorri"},
  {"vors"},
  {"vort"},
  {"voru"},
  {"vorum"},
  {"vér"},
  {"yfir"},
  {"ykkar"},
  {"ykkur"},
  {"yðar"},
  {"yður"},
  {"á"},
  {"án"},
  {"árla"},
  {"ásamt"},
  {"ég"},
  {"í"},
  {"óháð"},
  {"órafjarri"},
  {"öll"},
  {"öllu"},
  {"öllum"},
  {"önnur"},
  {"öðru"},
  {"öðrum"},
  {"úr"},
  {"út"},
  {"útundan"},
  {"ýmis"},
  {"ýmiss"},
  {"ýmissa"},
  {"ýmissar"},
  {"ýmissi"},
  {"ýmist"},
  {"ýmsa"},
  {"ýmsan"},
  {"ýmsar"},
  {"ýmsir"},
  {"ýmsu"},
  {"ýmsum"},
  {"þann"},
  {"þar"},
  {"þau"},
  {"það"},
  {"þegar"},
  {"þeim"},
  {"þeir"},
  {"þeirra"},
  {"þeirrar"},
  {"þeirri"},
  {"þennan"},
  {"þess"},
  {"þessa"},
  {"þessar"},
  {"þessara"},
  {"þessarar"},
  {"þessari"},
  {"þessi"},
  {"þessir"},
  {"þessu"},
  {"þessum"},
  {"þetta"},
  {"þig"},
  {"þinn"},
  {"þinna"},
  {"þinnar"},
  {"þinni"},
  {"þitt"},
  {"þið"},
  {"því"},
  {"þvílík"},
  {"þvílíka"},
  {"þvílíkan"},
  {"þvílíkar"},
  {"þvílíkir"},
  {"þvílíkra"},
  {"þvílíkrar"},
  {"þvílíkri"},
  {"þvílíks"},
  {"þvílíkt"},
  {"þvílíku"},
  {"þvílíkum"},
  {"þvílíkur"},
  {"þá"},
  {"þær"},
  {"þér"},
  {"þín"},
  {"þína"},
  {"þínar"},
  {"þínir"},
  {"þíns"},
  {"þínu"},
  {"þínum"},
  {"þó"},
  {"þónokkra"},
  {"þónokkrar"},
  {"þónokkrir"},
  {"þónokkru"},
  {"þónokkrum"},
  {"þónokkur"},
  {"þónokkurn"},
  {"þónokkurra"},
  {"þónokkurrar"},
  {"þónokkurri"},
  {"þónokkurs"},
  {"þónokkurt"},
  {"þónokkuð"},
  {"þótt"},
  {"þú"}
};

static const size_t ICELANDIC_STOPWORDS_COUNT = 590;

static const ContextualStopwordEntry ICELANDIC_CONTEXTUAL_STOPWORDS[] = {
  {"á", 24 },
  {"af", 24 },
  {"eftir", 24 },
  {"frá", 16 },
  {"fyrir", 24 },
  {"gegn", 16 },
  {"hjá", 16 },
  {"í", 16 },
  {"til", 16 },
  {"um", 16 },
  {"undir", 24 },
  {"úr", 16 },
  {"við", 48 },
  {"yfir", 24 }
};

static const size_t ICELANDIC_CONTEXTUAL_STOPWORDS_COUNT = 14;

static const DisambiguationRuleEntry ICELANDIC_DISAMBIGUATION_RULES[] = {
  {"á", POS_SO, POS_FS, CTX_AFTER_PRONOUN},
  {"á", POS_FS, POS_SO, CTX_BEFORE_NOUN},
  {"við", POS_FN, POS_FS, CTX_SENTENCE_START},
  {"við", POS_FS, POS_FN, CTX_BEFORE_NOUN},
  {"af", POS_FS, POS_AO, CTX_BEFORE_NOUN},
  {"til", POS_FS, POS_AO, CTX_BEFORE_NOUN},
  {"um", POS_FS, POS_AO, CTX_BEFORE_NOUN},
  {"yfir", POS_FS, POS_AO, CTX_BEFORE_NOUN},
  {"undir", POS_FS, POS_AO, CTX_BEFORE_NOUN},
  {"fyrir", POS_FS, POS_AO, CTX_BEFORE_NOUN},
  {"eftir", POS_FS, POS_AO, CTX_BEFORE_NOUN},
  {"frá", POS_FS, POS_AO, CTX_BEFORE_NOUN},
  {"með", POS_FS, POS_AO, CTX_BEFORE_NOUN},
  {"í", POS_FS, POS_AO, CTX_BEFORE_NOUN},
  {"úr", POS_FS, POS_NO, CTX_BEFORE_NOUN}
};

static const size_t ICELANDIC_DISAMBIGUATION_RULES_COUNT = 15;

static const PhraseEntry ICELANDIC_PHRASES[] = {
  {"á dögunum", "á dagur", true, POS_AO},
  {"á endanum", "á endi", true, POS_AO},
  {"á hinn bóginn", "á hinn bógur", true, POS_AO},
  {"á meðan", "á meðan", true, POS_AO},
  {"á morgun", "á morgunn", false, POS_AO},
  {"á ný", "á ný", true, POS_AO},
  {"á sama tíma", "á samur tími", true, POS_AO},
  {"á sínum tíma", "á sinn tími", true, POS_AO},
  {"að auki", "að auki", true, POS_AO},
  {"að minnsta kosti", "að lítill kostur", true, POS_AO},
  {"að nokkru leyti", "að nokkur leyti", true, POS_AO},
  {"að öllu leyti", "að allur leyti", true, POS_AO},
  {"að sjálfsögðu", "að sjálfsagður", true, POS_AO},
  {"að vísu", "að vís", true, POS_AO},
  {"af og til", "af og til", true, POS_AO},
  {"aftur á móti", "aftur á mót", true, POS_AO},
  {"alla vega", "allur vegur", true, POS_AO},
  {"alls ekki", "alls ekki", true, POS_AO},
  {"alls staðar", "allur staður", true, POS_AO},
  {"allt í allt", "allur í allur", true, POS_AO},
  {"annars vegar", "annar vegur", true, POS_AO},
  {"auk þess", "auk það", true, POS_AO},
  {"ef til vill", "ef til vilja", true, POS_AO},
  {"einhvern veginn", "einhver vegur", true, POS_AO},
  {"einhvers staðar", "einhver staður", true, POS_AO},
  {"einu sinni", "einn sinn", false, POS_AO},
  {"eitt sinn", "einn sinn", false, POS_AO},
  {"ekki síst", "ekki síður", true, POS_AO},
  {"engu að síður", "enginn að síður", true, POS_AO},
  {"evrópusambandið", "Evrópusambandið", false, POS_NO},
  {"fyrir aftan", "fyrir aftan", false, POS_FS},
  {"fyrir austan", "fyrir austan", false, POS_FS},
  {"fyrir framan", "fyrir framan", false, POS_FS},
  {"fyrir handan", "fyrir handan", false, POS_FS},
  {"fyrir hönd", "fyrir hönd", false, POS_FS},
  {"fyrir innan", "fyrir innan", false, POS_FS},
  {"fyrir neðan", "fyrir neðan", false, POS_FS},
  {"fyrir norðan", "fyrir norðan", false, POS_FS},
  {"fyrir ofan", "fyrir ofan", false, POS_FS},
  {"fyrir sunnan", "fyrir sunnan", false, POS_FS},
  {"fyrir utan", "fyrir utan", false, POS_FS},
  {"fyrir vestan", "fyrir vestan", false, POS_FS},
  {"fyrst og fremst", "snemma og fremri", true, POS_AO},
  {"hér á landi", "hér á land", true, POS_AO},
  {"hér og þar", "hér og þar", true, POS_AO},
  {"hér um bil", "hér um bil", true, POS_AO},
  {"hins vegar", "hinn vegur", true, POS_AO},
  {"hvað mest", "hvað mjög", true, POS_AO},
  {"hverju sinni", "hver sinn", true, POS_AO},
  {"hvorki né", "hvorki né", true, POS_AO},
  {"í burtu", "í burtu", true, POS_AO},
  {"í fyrsta sinn", "í fyrstur sinn", false, POS_AO},
  {"í gær", "í gær", true, POS_AO},
  {"í gegnum", "í gegnum", false, POS_FS},
  {"í kringum", "í kringum", false, POS_FS},
  {"í kvöld", "í kvöld", false, POS_AO},
  {"í ljósi", "í ljós", false, POS_FS},
  {"í morgun", "í morgunn", false, POS_AO},
  {"í raun", "í raun", true, POS_AO},
  {"í raun og veru", "í raun og vera", true, POS_AO},
  {"í senn", "í senn", true, POS_AO},
  {"í sífellu", "í sífella", true, POS_AO},
  {"í stað", "í staður", false, POS_FS},
  {"innan við", "innan við", false, POS_FS},
  {"lengi vel", "lengi vel", true, POS_AO},
  {"með öðrum orðum", "með annar orð", true, POS_AO},
  {"með tilliti til", "með tillit til", false, POS_FS},
  {"meðal annars", "meðal annar", true, POS_AO},
  {"meira að segja", "mikill að segja", true, POS_AO},
  {"meira og minna", "mikill og lítill", true, POS_AO},
  {"nato", "NATO", false, POS_NO},
  {"nató", "NATO", false, POS_NO},
  {"nokkurn veginn", "nokkur vegur", true, POS_AO},
  {"og svo framvegis", "og svo framvegis", true, POS_AO},
  {"sameinuðu þjóðirnar", "Sameinuðu þjóðirnar", false, POS_NO},
  {"satt að segja", "sannur að segja", true, POS_AO},
  {"sem betur fer", "sem vel fara", true, POS_AO},
  {"sér í lagi", "sér í lag", true, POS_AO},
  {"smám saman", "smátt saman", true, POS_AO},
  {"svo sem", "svo sem", true, POS_AO},
  {"til baka", "til baka", true, POS_AO},
  {"til dæmis", "til dæmi", true, POS_AO},
  {"til og frá", "til og frá", true, POS_AO},
  {"upp úr", "upp úr", false, POS_FS},
  {"vítt og breitt", "vítt og breitt", true, POS_AO},
  {"það er að segja", "það vera að segja", true, POS_AO},
  {"þar að auki", "þar að auki", true, POS_AO},
  {"þar af leiðandi", "þar af leiða", true, POS_AO},
  {"þar eð", "þar eð", true, POS_ST},
  {"þess vegna", "það vegna", true, POS_AO},
  {"þrátt fyrir", "þrátt fyrir", true, POS_AO},
  {"þvert á", "þvert á", false, POS_FS},
  {"því miður", "það lítt", true, POS_AO}
};

static const size_t ICELANDIC_PHRASES_COUNT = 93;

static const PrepositionCaseEntry ICELANDIC_PREP_CASES[] = {
  {"á", 6 },
  {"að", 4 },
  {"af", 4 },
  {"án", 8 },
  {"auk", 8 },
  {"frá", 4 },
  {"fyrir", 6 },
  {"gagnvart", 4 },
  {"gegn", 4 },
  {"gegnum", 2 },
  {"handa", 4 },
  {"hjá", 4 },
  {"í", 6 },
  {"í stað", 8 },
  {"innan", 8 },
  {"kringum", 2 },
  {"með", 6 },
  {"meðal", 8 },
  {"meðfram", 4 },
  {"milli", 8 },
  {"móti", 4 },
  {"nálægt", 4 },
  {"sakir", 8 },
  {"til", 8 },
  {"um", 2 },
  {"umhverfis", 2 },
  {"undir", 6 },
  {"úr", 4 },
  {"utan", 8 },
  {"vegna", 8 },
  {"við", 6 },
  {"yfir", 6 }
};

static const size_t ICELANDIC_PREP_CASES_COUNT = 32;

static const char *ICELANDIC_NOMINATIVE_PRONOUNS[] = {
  "hann",
  "hún",
  "við",
  "ég",
  "þau",
  "það",
  "þeir",
  "þið",
  "þær",
  "þú"
};

static const size_t ICELANDIC_NOMINATIVE_PRONOUNS_COUNT = 10;

static const char *ICELANDIC_PROTECTED_LEMMAS[] = {
  "akureyri",
  "alþingi",
  "arionbanki",
  "bandaríkin",
  "bergþórshvol",
  "blönduós",
  "bolungarvík",
  "borgarnes",
  "búðardalur",
  "dalvík",
  "danmörk",
  "djúpivogur",
  "egilsstaðir",
  "eistland",
  "england",
  "eskifjörður",
  "finnland",
  "flateyri",
  "frakkland",
  "fáskrúðsfjörður",
  "garðabær",
  "grikkland",
  "grindavík",
  "grundarfjörður",
  "grænland",
  "hafnarfjörður",
  "hlíðarendi",
  "holland",
  "hvammstangi",
  "hveragerði",
  "hólmavík",
  "höfn",
  "húsavík",
  "keflavík",
  "kópavogur",
  "landsbankinn",
  "lettland",
  "litháen",
  "mosfellsbær",
  "neskaupstaður",
  "noregur",
  "patreksfjörður",
  "portúgal",
  "pólland",
  "reykjavík",
  "reyðarfjörður",
  "rússland",
  "sandgerði",
  "sauðárkrókur",
  "selfoss",
  "seltjarnarnes",
  "seyðisfjörður",
  "siglufjörður",
  "skagaströnd",
  "skotland",
  "spánn",
  "stykkishólmur",
  "stöðvarfjörður",
  "suðureyri",
  "svissland",
  "svíþjóð",
  "tékkland",
  "varmahlíð",
  "vestmannaeyjar",
  "vík",
  "írland",
  "ísafjörður",
  "ísland",
  "íslandsbanki",
  "ítalía",
  "ólafsfjörður",
  "ólafsvík",
  "þingvellir",
  "þorlákshöfn",
  "þýskaland"
};

static const size_t ICELANDIC_PROTECTED_LEMMAS_COUNT = 75;

static const char *ICELANDIC_COMMON_COMPOUND_TAILS[] = {
  "banki",
  "borg",
  "bær",
  "dalur",
  "fjörður",
  "formaður",
  "forseti",
  "fulltrúi",
  "félag",
  "greiðsla",
  "hús",
  "kerfi",
  "kona",
  "kostnaður",
  "maður",
  "mál",
  "rannsókn",
  "rekstur",
  "ráð",
  "ráðherra",
  "sjóður",
  "starfsmaður",
  "staður",
  "stjóri",
  "stofnun",
  "vegur",
  "verk",
  "verð",
  "viðskipti",
  "þjónusta"
};

static const size_t ICELANDIC_COMMON_COMPOUND_TAILS_COUNT = 30;

static const char *ICELANDIC_COMMON_STANDALONE[] = {
  "búa",
  "eiga",
  "fara",
  "gera",
  "geta",
  "hafa",
  "halda",
  "koma",
  "leyfa",
  "láta",
  "mega",
  "segja",
  "sjá",
  "taka",
  "vera",
  "verða",
  "vilja",
  "þurfa"
};

static const size_t ICELANDIC_COMMON_STANDALONE_COUNT = 18;
